//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_imagen
    {
        public int id { get; set; }
        public byte[] imagen { get; set; }
        public int id_informacion_imagen { get; set; }
        public Nullable<int> id_persona { get; set; }
        public Nullable<int> id_vehiculo { get; set; }
        public Nullable<int> id_objeto { get; set; }
    
        public virtual tb_informacion_imagen tb_informacion_imagen { get; set; }
        public virtual tb_objeto tb_objeto { get; set; }
        public virtual tb_persona tb_persona { get; set; }
        public virtual tb_vehiculo tb_vehiculo { get; set; }
    }
}
