//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_oficial_policia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_oficial_policia()
        {
            this.tb_persona = new HashSet<tb_persona>();
        }
    
        public int id { get; set; }
        public int id_policia { get; set; }
        public int id_unidad { get; set; }
        public int id_placa { get; set; }
        public int id_caseta { get; set; }
    
        public virtual tb_caseta tb_caseta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_persona> tb_persona { get; set; }
        public virtual tb_placa tb_placa { get; set; }
        public virtual tb_policia tb_policia { get; set; }
        public virtual tb_unidad tb_unidad { get; set; }
    }
}
