//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_subcategoria_delito
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_subcategoria_delito()
        {
            this.tb_informacion_basica = new HashSet<tb_informacion_basica>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
        public int id_categoria_delito { get; set; }
    
        public virtual tb_categoria_delito tb_categoria_delito { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_informacion_basica> tb_informacion_basica { get; set; }
    }
}
