//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_informacion_basica
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_informacion_basica()
        {
            this.tb_delito_secundario = new HashSet<tb_delito_secundario>();
        }
    
        public int id { get; set; }
        public int id_origen { get; set; }
        public string numero_unico { get; set; }
        public int id_subcategoria_delito { get; set; }
        public Nullable<int> id_modalidad { get; set; }
        public int id_subvictima { get; set; }
        public System.DateTime fecha_ingreso { get; set; }
        public int id_oficina_encargado { get; set; }
        public int id_delegacion { get; set; }
        public string perjuicio { get; set; }
        public string moneda { get; set; }
        public int tentativo { get; set; }
        public string observaciones { get; set; }
        public string narracion { get; set; }
        public int id_hecho { get; set; }
    
        public virtual tb_delegacion tb_delegacion { get; set; }
        public virtual tb_hecho tb_hecho { get; set; }
        public virtual tb_modalidad tb_modalidad { get; set; }
        public virtual tb_oficina_encargado tb_oficina_encargado { get; set; }
        public virtual tb_origen tb_origen { get; set; }
        public virtual tb_subcategoria_delito tb_subcategoria_delito { get; set; }
        public virtual tb_subvictima tb_subvictima { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_delito_secundario> tb_delito_secundario { get; set; }
    }
}
