//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_objeto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_objeto()
        {
            this.tb_imagen = new HashSet<tb_imagen>();
        }
    
        public int id { get; set; }
        public int id_subtipo { get; set; }
        public string serie { get; set; }
        public string modelo { get; set; }
        public string marca { get; set; }
        public int id_color { get; set; }
        public string descripcion { get; set; }
        public string nombre_entidad { get; set; }
        public int id_intensidad { get; set; }
        public string atributo { get; set; }
        public int decomisado { get; set; }
        public string observaciones { get; set; }
        public int id_rol { get; set; }
    
        public virtual tb_color tb_color { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_imagen> tb_imagen { get; set; }
        public virtual tb_intensidad tb_intensidad { get; set; }
        public virtual tb_rol tb_rol { get; set; }
        public virtual tb_subtipo tb_subtipo { get; set; }
    }
}
