//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_opcion_detalle_persona
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_opcion_detalle_persona()
        {
            this.tb_valor_opcion_detalle_persona = new HashSet<tb_valor_opcion_detalle_persona>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
        public Nullable<int> id_detalle_persona { get; set; }
    
        public virtual tb_detalle_persona tb_detalle_persona { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_valor_opcion_detalle_persona> tb_valor_opcion_detalle_persona { get; set; }
    }
}
