//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_persona_juridica
    {
        public int id { get; set; }
        public string cedula_juridica { get; set; }
        public string razon_social { get; set; }
        public int id_nombre_fantasia { get; set; }
        public string filial { get; set; }
        public int id_estado { get; set; }
        public string nombre_entidad { get; set; }
        public int id_intensidad { get; set; }
        public string atributo { get; set; }
        public int allanada { get; set; }
        public string observaciones { get; set; }
        public int id_rol { get; set; }
    
        public virtual tb_estado tb_estado { get; set; }
        public virtual tb_intensidad tb_intensidad { get; set; }
        public virtual tb_nombre_fantasia tb_nombre_fantasia { get; set; }
        public virtual tb_rol tb_rol { get; set; }
    }
}
